package com.android.gatherly.viewmodel.groups.edit

import com.android.gatherly.model.group.Group
import com.android.gatherly.model.profile.Profile

// This file contains code generated by an LLM (Claude.ai).

/**
 * Test data for [EditGroupViewModelTest].
 *
 * Provides sample profiles, groups, and constants used across multiple test cases to ensure
 * consistency and readability.
 */
object EditGroupViewModelTestData {
  const val TEST_USER_ID = "testUser123"
  const val TEST_GROUP_ID = "testGroup456"

  // Current user profile
  val CURRENT_USER_PROFILE =
      Profile(
          uid = TEST_USER_ID,
          name = "Test User",
          username = "testuser",
          friendUids = listOf("alice123", "bob456", "charlie789", "david012"))

  // Friends who are current group members
  val MEMBER_ALICE =
      Profile(uid = "alice123", name = "Alice Smith", username = "alice", friendUids = emptyList())

  val MEMBER_BOB =
      Profile(uid = "bob456", name = "Bob Johnson", username = "bob", friendUids = emptyList())

  // Friends who are NOT in the group (available to add)
  val FRIEND_CHARLIE =
      Profile(
          uid = "charlie789",
          name = "Charlie Brown",
          username = "charlie",
          friendUids = emptyList())

  val FRIEND_DAVID =
      Profile(uid = "david012", name = "David Lee", username = "david", friendUids = emptyList())

  val ALL_FRIENDS = listOf(MEMBER_ALICE, MEMBER_BOB, FRIEND_CHARLIE, FRIEND_DAVID)

  // Test group with Alice and Bob as members, Alice as admin
  val TEST_GROUP =
      Group(
          gid = TEST_GROUP_ID,
          creatorId = TEST_USER_ID,
          name = "Study Group",
          description = "Weekly study sessions",
          memberIds = listOf(TEST_USER_ID, MEMBER_ALICE.uid, MEMBER_BOB.uid),
          adminIds = listOf(TEST_USER_ID, MEMBER_ALICE.uid))

  // Group with no description
  val GROUP_NO_DESCRIPTION =
      Group(
          gid = "group789",
          creatorId = TEST_USER_ID,
          name = "Simple Group",
          description = null,
          memberIds = listOf(TEST_USER_ID),
          adminIds = listOf(TEST_USER_ID))
}
