package com.android.gatherly.viewmodel.groups.edit

import com.android.gatherly.model.notification.NotificationsLocalRepository
import com.android.gatherly.model.notification.NotificationsRepository
import com.android.gatherly.model.points.PointsLocalRepository
import com.android.gatherly.model.points.PointsRepository
import com.android.gatherly.model.profile.ProfileLocalRepository
import com.android.gatherly.ui.groups.EditGroupViewModel
import com.android.gatherly.utilstest.MockitoUtils
import com.android.gatherly.viewmodel.FakeGroupsRepositoryLocal
import com.android.gatherly.viewmodel.groups.edit.EditGroupViewModelTestData.ALL_FRIENDS
import com.android.gatherly.viewmodel.groups.edit.EditGroupViewModelTestData.CURRENT_USER_PROFILE
import com.android.gatherly.viewmodel.groups.edit.EditGroupViewModelTestData.FRIEND_CHARLIE
import com.android.gatherly.viewmodel.groups.edit.EditGroupViewModelTestData.FRIEND_DAVID
import com.android.gatherly.viewmodel.groups.edit.EditGroupViewModelTestData.GROUP_NO_DESCRIPTION
import com.android.gatherly.viewmodel.groups.edit.EditGroupViewModelTestData.MEMBER_ALICE
import com.android.gatherly.viewmodel.groups.edit.EditGroupViewModelTestData.MEMBER_BOB
import com.android.gatherly.viewmodel.groups.edit.EditGroupViewModelTestData.TEST_GROUP
import com.android.gatherly.viewmodel.groups.edit.EditGroupViewModelTestData.TEST_GROUP_ID
import com.android.gatherly.viewmodel.groups.edit.EditGroupViewModelTestData.TEST_USER_ID
import kotlin.time.Duration.Companion.seconds
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.test.UnconfinedTestDispatcher
import kotlinx.coroutines.test.advanceUntilIdle
import kotlinx.coroutines.test.resetMain
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import org.junit.After
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test

// This file contains code generated by an LLM (Claude.ai).

/**
 * Unit tests for [EditGroupViewModel].
 *
 * Tests the group editing flow including loading existing groups, member management (add/remove),
 * admin promotion/demotion, field validation, and saving updates. Uses fake repositories and mocked
 * Firebase Auth to isolate business logic from external dependencies.
 *
 * Test categories:
 * - Initial state verification
 * - Group loading (success, not found, member profiles, friends list)
 * - Input field updates (name, description)
 * - Member management (add friends, remove members, toggle admin)
 * - Group saving (valid updates, validation failures, repository errors)
 * - State clearing methods
 */
@OptIn(ExperimentalCoroutinesApi::class)
class EditGroupViewModelTest {

  private lateinit var groupsRepository: FakeGroupsRepositoryLocal
  private lateinit var profileRepository: ProfileLocalRepository
  private lateinit var notificationsRepository: NotificationsRepository
  private lateinit var pointsRepository: PointsRepository
  private lateinit var mockitoUtils: MockitoUtils

  private val testDispatcher = UnconfinedTestDispatcher()
  val testTimeout = 120.seconds

  /**
   * Sets up test fixtures before each test.
   *
   * Initializes fake repositories with test data, mocks Firebase Auth to return a test user ID,
   * populates the profile repository with the current user and their friends, and adds the test
   * group to the groups repository. Sets the Main dispatcher to the test dispatcher for proper
   * coroutine testing.
   */
  @Before
  fun setup() {
    Dispatchers.setMain(testDispatcher)

    groupsRepository = FakeGroupsRepositoryLocal(currentUserId = TEST_USER_ID)
    profileRepository = ProfileLocalRepository()
    notificationsRepository = NotificationsLocalRepository()
    pointsRepository = PointsLocalRepository()

    // Mock Firebase Auth
    mockitoUtils = MockitoUtils()
    mockitoUtils.chooseCurrentUser(TEST_USER_ID)

    // Populate profile repository with test data
    runBlocking {
      profileRepository.addProfile(CURRENT_USER_PROFILE)
      ALL_FRIENDS.forEach { friend -> profileRepository.addProfile(friend) }
    }

    // Add test group to repository
    runBlocking { groupsRepository.addGroup(TEST_GROUP) }
  }

  /** Cleans up after each test by resetting the Main dispatcher. */
  @After
  fun tearDown() {
    Dispatchers.resetMain()
  }

  /** Creates an instance of [EditGroupViewModel] with the test repositories and mocked auth. */
  private fun createViewModel(): EditGroupViewModel {
    return EditGroupViewModel(
        groupsRepository = groupsRepository,
        profileRepository = profileRepository,
        notificationsRepository = notificationsRepository,
        pointsRepository = pointsRepository,
        authProvider = { mockitoUtils.mockAuth })
  }

  /**
   * Verifies that the ViewModel initializes with correct default empty values.
   *
   * Before loadGroup() is called, all fields should be empty/default.
   */
  @Test
  fun initialState_IsCorrect() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()

        val state = viewModel.uiState.value
        assertEquals("", state.groupId)
        assertEquals("", state.name)
        assertEquals("", state.description)
        assertNull(state.nameError)
        assertTrue(state.currentMemberProfiles.isEmpty())
        assertTrue(state.adminIds.isEmpty())
        assertTrue(state.friendsList.isEmpty())
        assertTrue(state.availableFriendsToAdd.isEmpty())
        assertTrue(state.selectedNewFriendIds.isEmpty())
        assertTrue(state.membersToRemove.isEmpty())
        assertFalse(state.isLoading)
        assertNull(state.loadError)
        assertFalse(state.isSaving)
        assertNull(state.saveError)
        assertFalse(state.saveSuccess)
      }

  /**
   * Verifies that loadGroup() successfully loads an existing group and populates the UI state.
   *
   * Tests that the group's basic fields, member profiles, and available friends list are correctly
   * loaded.
   */
  @Test
  fun loadGroup_LoadsGroupSuccessfully() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()

        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        val state = viewModel.uiState.value
        assertEquals(TEST_GROUP_ID, state.groupId)
        assertEquals("Study Group", state.name)
        assertEquals("Weekly study sessions", state.description)
        assertEquals(listOf(TEST_USER_ID, MEMBER_ALICE.uid), state.adminIds)
        assertFalse(state.isLoading)
        assertNull(state.loadError)

        // Verify member profiles loaded
        assertEquals(3, state.currentMemberProfiles.size)
        assertTrue(state.currentMemberProfiles.any { it.uid == MEMBER_ALICE.uid })
        assertTrue(state.currentMemberProfiles.any { it.uid == MEMBER_BOB.uid })

        // Verify friends list loaded (only non-members available to add)
        assertEquals(2, state.availableFriendsToAdd.size)
        assertTrue(state.availableFriendsToAdd.contains(FRIEND_CHARLIE))
        assertTrue(state.availableFriendsToAdd.contains(FRIEND_DAVID))
      }

  /**
   * Verifies that loadGroup() handles a group with null description correctly.
   *
   * Tests that null descriptions are converted to empty strings in the UI state.
   */
  @Test
  fun loadGroup_WithNullDescription_LoadsEmptyString() =
      runTest(testDispatcher, testTimeout) {
        runBlocking { groupsRepository.addGroup(GROUP_NO_DESCRIPTION) }

        val viewModel = createViewModel()
        viewModel.loadGroup(GROUP_NO_DESCRIPTION.gid)
        advanceUntilIdle()

        val state = viewModel.uiState.value
        assertEquals("Simple Group", state.name)
        assertEquals("", state.description) // null converted to empty string
      }

  /**
   * Verifies that loadGroup() sets an error when the group is not found.
   *
   * Tests the error handling path when trying to load a non-existent group.
   */
  @Test
  fun loadGroup_GroupNotFound_SetsLoadError() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()

        viewModel.loadGroup("nonexistentGroupId")
        advanceUntilIdle()

        val state = viewModel.uiState.value
        assertFalse(state.isLoading)
        assertNotNull(state.loadError)
        assertTrue(state.loadError!!.contains("not found"))
      }

  /**
   * Verifies that loadGroup() continues successfully even if some member profiles cannot be
   * fetched.
   *
   * Tests the resilience of member profile loading - missing profiles should be skipped without
   * causing the entire operation to fail.
   */
  @Test
  fun loadGroup_SkipsMembersThatCannotBeFetched() =
      runTest(testDispatcher, testTimeout) {
        // Remove Bob's profile
        profileRepository.deleteProfile(MEMBER_BOB.uid)

        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        val state = viewModel.uiState.value
        // Should load successfully with only 2 member profiles
        assertEquals(2, state.currentMemberProfiles.size)
        assertTrue(state.currentMemberProfiles.any { it.uid == MEMBER_ALICE.uid })
        assertFalse(state.currentMemberProfiles.any { it.uid == MEMBER_BOB.uid })
        assertNull(state.loadError)
      }

  /**
   * Verifies that loadGroup() continues successfully even if some friends cannot be fetched.
   *
   * Tests the resilience of friends list loading - missing friend profiles should be skipped
   * without causing the entire operation to fail.
   */
  @Test
  fun loadGroup_SkipsFriendsThatCannotBeFetched() =
      runTest(testDispatcher, testTimeout) {
        // Remove Charlie's profile
        profileRepository.deleteProfile(FRIEND_CHARLIE.uid)

        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        val state = viewModel.uiState.value
        // Should load successfully with only David in available friends
        assertEquals(1, state.availableFriendsToAdd.size)
        assertTrue(state.availableFriendsToAdd.contains(FRIEND_DAVID))
        assertFalse(state.availableFriendsToAdd.contains(FRIEND_CHARLIE))
      }

  /**
   * Verifies that loadGroup() handles authentication errors gracefully.
   *
   * Tests that when no user is signed in, the friends list remains empty but the group still loads.
   */
  @Test
  fun loadGroup_NoAuthenticatedUser_LoadsGroupWithoutFriends() =
      runTest(testDispatcher, testTimeout) {
        mockitoUtils.unauthenticatedCurrentUser()

        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        val state = viewModel.uiState.value
        // Group should still load
        assertEquals(TEST_GROUP_ID, state.groupId)
        assertEquals("Study Group", state.name)
        // But friends list should be empty
        assertTrue(state.friendsList.isEmpty())
        assertTrue(state.availableFriendsToAdd.isEmpty())
        assertNull(state.loadError) // No error, just silently fails friends loading
      }

  /**
   * Verifies that a valid name updates the state and clears any validation errors.
   *
   * Tests the happy path for name input where the value is non-blank.
   */
  @Test
  fun onNameChanged_ValidName_UpdatesStateAndClearsError() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        viewModel.onNameChanged("Updated Study Group")

        val state = viewModel.uiState.value
        assertEquals("Updated Study Group", state.name)
        assertNull(state.nameError)
      }

  /**
   * Verifies that a blank name triggers a validation error.
   *
   * Tests that an empty string name results in an appropriate error message.
   */
  @Test
  fun onNameChanged_BlankName_SetsError() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        viewModel.onNameChanged("")

        val state = viewModel.uiState.value
        assertEquals("", state.name)
        assertEquals("Name cannot be empty", state.nameError)
      }

  /**
   * Verifies that a whitespace-only name triggers a validation error.
   *
   * Tests that names containing only spaces are treated as blank and trigger validation errors.
   */
  @Test
  fun onNameChanged_WhitespaceName_SetsError() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        viewModel.onNameChanged("   ")

        val state = viewModel.uiState.value
        assertEquals("   ", state.name)
        assertEquals("Name cannot be empty", state.nameError)
      }

  /**
   * Verifies that description changes are correctly reflected in the UI state.
   *
   * Tests that the description field updates without validation (description is optional).
   */
  @Test
  fun onDescriptionChanged_UpdatesState() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        viewModel.onDescriptionChanged("Updated description for the group")

        val state = viewModel.uiState.value
        assertEquals("Updated description for the group", state.description)
      }

  /**
   * Verifies that toggling an unselected friend adds them to the selected new friends list.
   *
   * Tests the friend selection mechanism for adding new members to the group.
   */
  @Test
  fun onNewFriendToggled_SelectsFriend() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        viewModel.onNewFriendToggled(FRIEND_CHARLIE.uid)

        val state = viewModel.uiState.value
        assertTrue(state.selectedNewFriendIds.contains(FRIEND_CHARLIE.uid))
        assertEquals(1, state.selectedNewFriendIds.size)
      }

  /**
   * Verifies that toggling a selected friend removes them from the selected new friends list.
   *
   * Tests the friend deselection mechanism for removing a friend from the add list.
   */
  @Test
  fun onNewFriendToggled_DeselectsFriend() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        // Select then deselect
        viewModel.onNewFriendToggled(FRIEND_CHARLIE.uid)
        viewModel.onNewFriendToggled(FRIEND_CHARLIE.uid)

        val state = viewModel.uiState.value
        assertFalse(state.selectedNewFriendIds.contains(FRIEND_CHARLIE.uid))
        assertTrue(state.selectedNewFriendIds.isEmpty())
      }

  /**
   * Verifies that multiple friends can be selected simultaneously.
   *
   * Tests that the selection mechanism correctly maintains a list of multiple selected friends.
   */
  @Test
  fun onNewFriendToggled_SelectMultipleFriends() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        viewModel.onNewFriendToggled(FRIEND_CHARLIE.uid)
        viewModel.onNewFriendToggled(FRIEND_DAVID.uid)

        val state = viewModel.uiState.value
        assertEquals(2, state.selectedNewFriendIds.size)
        assertTrue(state.selectedNewFriendIds.contains(FRIEND_CHARLIE.uid))
        assertTrue(state.selectedNewFriendIds.contains(FRIEND_DAVID.uid))
      }

  /**
   * Verifies that toggling a member marks them for removal.
   *
   * Tests the member removal marking mechanism.
   */
  @Test
  fun onToggleRemoveMember_MarksMemberForRemoval() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        viewModel.onToggleRemoveMember(MEMBER_BOB.uid)

        val state = viewModel.uiState.value
        assertTrue(state.membersToRemove.contains(MEMBER_BOB.uid))
        assertEquals(1, state.membersToRemove.size)
      }

  /**
   * Verifies that toggling a marked member unmarks them from removal.
   *
   * Tests the member removal unmarking mechanism.
   */
  @Test
  fun onToggleRemoveMember_UnmarksMember() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        // Mark then unmark
        viewModel.onToggleRemoveMember(MEMBER_BOB.uid)
        viewModel.onToggleRemoveMember(MEMBER_BOB.uid)

        val state = viewModel.uiState.value
        assertFalse(state.membersToRemove.contains(MEMBER_BOB.uid))
        assertTrue(state.membersToRemove.isEmpty())
      }

  /**
   * Verifies that multiple members can be marked for removal simultaneously.
   *
   * Tests that the removal marking mechanism correctly maintains a list of multiple members.
   */
  @Test
  fun onToggleRemoveMember_MarkMultipleMembers() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        viewModel.onToggleRemoveMember(MEMBER_ALICE.uid)
        viewModel.onToggleRemoveMember(MEMBER_BOB.uid)

        val state = viewModel.uiState.value
        assertEquals(2, state.membersToRemove.size)
        assertTrue(state.membersToRemove.contains(MEMBER_ALICE.uid))
        assertTrue(state.membersToRemove.contains(MEMBER_BOB.uid))
      }

  /**
   * Verifies that toggling a non-admin member promotes them to admin.
   *
   * Tests the admin promotion mechanism.
   */
  @Test
  fun onToggleAdmin_PromotesMemberToAdmin() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        // Bob is not an admin initially
        viewModel.onToggleAdmin(MEMBER_BOB.uid)

        val state = viewModel.uiState.value
        assertTrue(state.adminIds.contains(MEMBER_BOB.uid))
      }

  /**
   * Verifies that toggling an admin member demotes them from admin.
   *
   * Tests the admin demotion mechanism.
   */
  @Test
  fun onToggleAdmin_DemotesAdminToMember() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        // Alice is an admin initially
        viewModel.onToggleAdmin(MEMBER_ALICE.uid)

        val state = viewModel.uiState.value
        assertFalse(state.adminIds.contains(MEMBER_ALICE.uid))
      }

  /**
   * Verifies that a group is successfully updated with valid data.
   *
   * Tests the complete save flow with name and description updates. Verifies that the group is
   * updated in the repository with correct values.
   */
  @Test
  fun saveGroup_WithValidData_UpdatesGroup() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        viewModel.onNameChanged("Updated Study Group")
        viewModel.onDescriptionChanged("New description")

        viewModel.saveGroup()
        advanceUntilIdle()

        val state = viewModel.uiState.value
        assertTrue(state.saveSuccess)
        assertFalse(state.isSaving)
        assertNull(state.saveError)

        // Verify group was updated in repository
        val updatedGroup = groupsRepository.getGroup(TEST_GROUP_ID)
        assertEquals("Updated Study Group", updatedGroup.name)
        assertEquals("New description", updatedGroup.description)
      }

  /**
   * Verifies that new friends are added to the group when saving.
   *
   * Tests that selected friends are correctly added to the member list.
   */
  @Test
  fun saveGroup_WithNewFriends_AddsMembersToGroup() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        viewModel.onNewFriendToggled(FRIEND_CHARLIE.uid)
        viewModel.onNewFriendToggled(FRIEND_DAVID.uid)

        viewModel.saveGroup()
        advanceUntilIdle()

        assertTrue(viewModel.uiState.value.saveSuccess)

        val updatedGroup = groupsRepository.getGroup(TEST_GROUP_ID)
        assertTrue(updatedGroup.memberIds.contains(FRIEND_CHARLIE.uid))
        assertTrue(updatedGroup.memberIds.contains(FRIEND_DAVID.uid))
        assertEquals(5, updatedGroup.memberIds.size) // original 3 + 2 new
      }

  /**
   * Verifies that marked members are removed from the group when saving.
   *
   * Tests that members marked for removal are correctly removed from the member list.
   */
  @Test
  fun saveGroup_WithRemovedMembers_RemovesMembersFromGroup() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        viewModel.onToggleRemoveMember(MEMBER_BOB.uid)

        viewModel.saveGroup()
        advanceUntilIdle()

        assertTrue(viewModel.uiState.value.saveSuccess)

        val updatedGroup = groupsRepository.getGroup(TEST_GROUP_ID)
        assertFalse(updatedGroup.memberIds.contains(MEMBER_BOB.uid))
        assertEquals(2, updatedGroup.memberIds.size) // original 3 - 1 removed
      }

  /**
   * Verifies that admin status updates are persisted when saving.
   *
   * Tests that admin promotions and demotions are correctly saved.
   */
  @Test
  fun saveGroup_WithAdminChanges_UpdatesAdminList() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        // Promote Bob to admin
        viewModel.onToggleAdmin(MEMBER_BOB.uid)
        // Demote Alice from admin
        viewModel.onToggleAdmin(MEMBER_ALICE.uid)

        viewModel.saveGroup()
        advanceUntilIdle()

        assertTrue(viewModel.uiState.value.saveSuccess)

        val updatedGroup = groupsRepository.getGroup(TEST_GROUP_ID)
        assertTrue(updatedGroup.adminIds.contains(MEMBER_BOB.uid))
        assertFalse(updatedGroup.adminIds.contains(MEMBER_ALICE.uid))
        assertTrue(updatedGroup.adminIds.contains(TEST_USER_ID)) // Creator still admin
      }

  /**
   * Verifies that removing a member also removes their admin status.
   *
   * Tests that the ViewModel correctly filters out admins who are no longer members.
   */
  @Test
  fun saveGroup_RemovingAdmin_RemovesTheirAdminStatus() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        // Mark Alice (who is an admin) for removal
        viewModel.onToggleRemoveMember(MEMBER_ALICE.uid)

        viewModel.saveGroup()
        advanceUntilIdle()

        assertTrue(viewModel.uiState.value.saveSuccess)

        val updatedGroup = groupsRepository.getGroup(TEST_GROUP_ID)
        assertFalse(updatedGroup.memberIds.contains(MEMBER_ALICE.uid))
        assertFalse(updatedGroup.adminIds.contains(MEMBER_ALICE.uid))
      }

  /**
   * Verifies that complex updates (add, remove, admin changes) all work together.
   *
   * Tests a realistic scenario with multiple simultaneous changes.
   */
  @Test
  fun saveGroup_WithMultipleChanges_UpdatesAllCorrectly() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        // Add new friend
        viewModel.onNewFriendToggled(FRIEND_CHARLIE.uid)
        // Remove existing member
        viewModel.onToggleRemoveMember(MEMBER_BOB.uid)
        // Promote Alice (already admin, so this demotes)
        viewModel.onToggleAdmin(MEMBER_ALICE.uid)
        // Update name and description
        viewModel.onNameChanged("Revised Study Group")
        viewModel.onDescriptionChanged("Updated description")

        viewModel.saveGroup()
        advanceUntilIdle()

        assertTrue(viewModel.uiState.value.saveSuccess)

        val updatedGroup = groupsRepository.getGroup(TEST_GROUP_ID)
        assertEquals("Revised Study Group", updatedGroup.name)
        assertEquals("Updated description", updatedGroup.description)
        assertTrue(updatedGroup.memberIds.contains(FRIEND_CHARLIE.uid))
        assertFalse(updatedGroup.memberIds.contains(MEMBER_BOB.uid))
        assertFalse(updatedGroup.adminIds.contains(MEMBER_ALICE.uid))
      }

  /**
   * Verifies that a group with a blank description saves with null description.
   *
   * Tests that empty/blank descriptions are converted to null in the saved group.
   */
  @Test
  fun saveGroup_WithBlankDescription_SavesWithNullDescription() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        viewModel.onDescriptionChanged("")

        viewModel.saveGroup()
        advanceUntilIdle()

        assertTrue(viewModel.uiState.value.saveSuccess)

        val updatedGroup = groupsRepository.getGroup(TEST_GROUP_ID)
        assertNull(updatedGroup.description)
      }

  /**
   * Verifies that save is prevented when the group name is blank.
   *
   * Tests that validation errors prevent group updates and no changes are saved to the repository.
   */
  @Test
  fun saveGroup_WithBlankName_DoesNotSave() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        viewModel.onNameChanged("")

        viewModel.saveGroup()
        advanceUntilIdle()

        val state = viewModel.uiState.value
        assertFalse(state.saveSuccess)
        assertEquals("Name cannot be empty", state.nameError)
        assertFalse(state.isSaving)

        // Verify group was not changed
        val unchangedGroup = groupsRepository.getGroup(TEST_GROUP_ID)
        assertEquals("Study Group", unchangedGroup.name) // Original name
      }

  /**
   * Verifies that save is prevented when the group name contains only whitespace.
   *
   * Tests that whitespace-only names are treated as blank and validation prevents saving.
   */
  @Test
  fun saveGroup_WithWhitespaceName_DoesNotSave() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        viewModel.onNameChanged("   ")

        viewModel.saveGroup()
        advanceUntilIdle()

        val state = viewModel.uiState.value
        assertFalse(state.saveSuccess)
        assertEquals("Name cannot be empty", state.nameError)

        val unchangedGroup = groupsRepository.getGroup(TEST_GROUP_ID)
        assertEquals("Study Group", unchangedGroup.name)
      }

  /**
   * Verifies that the saving state flag is correctly managed during the save operation.
   *
   * Tests that isSaving is false before and after the save completes.
   */
  @Test
  fun saveGroup_SetsSavingStateCorrectly() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        // Before save
        assertFalse(viewModel.uiState.value.isSaving)

        viewModel.saveGroup()
        advanceUntilIdle()

        // After save
        assertFalse(viewModel.uiState.value.isSaving)
      }

  /**
   * Verifies that clearErrorMsg() removes both save and load errors from the UI state.
   *
   * Tests the error clearing mechanism after failures.
   */
  @Test
  fun clearErrorMsg_ClearsAllErrors() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()

        // Trigger a load error
        viewModel.loadGroup("nonexistentGroupId")
        advanceUntilIdle()

        assertNotNull(viewModel.uiState.value.loadError)

        viewModel.clearErrorMsg()

        assertNull(viewModel.uiState.value.loadError)
        assertNull(viewModel.uiState.value.saveError)
      }

  /**
   * Verifies that clearSaveSuccess() removes the save success flag from the UI state.
   *
   * Tests the success flag clearing mechanism after a successful save.
   */
  @Test
  fun clearSaveSuccess_ClearsSaveSuccessFlag() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        viewModel.saveGroup()
        advanceUntilIdle()

        assertTrue(viewModel.uiState.value.saveSuccess)

        viewModel.clearSaveSuccess()

        assertFalse(viewModel.uiState.value.saveSuccess)
      }

  /**
   * Verifies that repository exceptions during save are properly handled.
   *
   * Tests that when the repository throws an exception, the error is captured in the UI state and
   * no changes are persisted.
   */
  @Test
  fun saveGroup_RepositoryThrowsException_SetsSaveError() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()
        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        groupsRepository.shouldThrowOnEditGroup = true

        viewModel.onNameChanged("Try to change this")
        viewModel.saveGroup()
        advanceUntilIdle()

        val state = viewModel.uiState.value
        assertFalse(state.saveSuccess)
        assertNotNull(state.saveError)
        assertEquals("Test error", state.saveError)
        assertFalse(state.isSaving)
      }

  /**
   * Verifies that the loading state flag is correctly managed during group loading.
   *
   * Tests that isLoading is false after the load completes.
   */
  @Test
  fun loadGroup_SetsLoadingStateCorrectly() =
      runTest(testDispatcher, testTimeout) {
        val viewModel = createViewModel()

        // Before load
        assertFalse(viewModel.uiState.value.isLoading)

        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        // After load
        assertFalse(viewModel.uiState.value.isLoading)
      }

  /**
   * Verifies that deleteGroup() deletes the loaded group from the repository. After deletion,
   * fetching the group should fail.
   */
  @Test
  fun deleteGroup_WithLoadedGroup_DeletesGroupFromRepository() =
      runTest(testDispatcher) {
        val viewModel = createViewModel()

        viewModel.loadGroup(TEST_GROUP_ID)
        advanceUntilIdle()

        viewModel.deleteGroup()
        advanceUntilIdle()

        try {
          groupsRepository.getGroup(TEST_GROUP_ID)
          fail("Expected group to be deleted, but it was still found.")
        } catch (e: Exception) {}
        assertNull(viewModel.uiState.value.saveError)
      }

  /** Verifies that deleteGroup() does nothing if given blank groupId. */
  @Test
  fun deleteGroupWithBlankGroupIdDoesNothing() =
      runTest(testDispatcher) {
        val viewModel = createViewModel()

        viewModel.deleteGroup()
        advanceUntilIdle()

        val group = groupsRepository.getGroup(TEST_GROUP_ID)
        assertEquals("Study Group", group.name)
      }
}
