// Part of this code was generated by an LLM (ChatGPT)

// Initializes the firebase functions and gives admin rights to reset values

const {onSchedule} = require("firebase-functions/v2/scheduler");
const admin = require("firebase-admin");
const logger = require("firebase-functions/logger");

admin.initializeApp();

// Function that resets every monday at 00:00 Paris time
exports.weeklyReset = onSchedule(
    "0 0 * * MON",
    {timeZone: "Europe/Paris"},
    async (event) => {
      try {
        const db = admin.firestore();
        const usersSnapshot = await db.collection("profiles").get();

        const batch = db.batch();
        usersSnapshot.forEach((doc) => {
          batch.update(doc.ref, {weeklyPoints: 0.0});
        });

        await batch.commit();

        logger.info("Weekly reset executed successfully");
      } catch (err) {
        logger.error("Weekly reset failed", err);
      }
    },
);
