// Part of this code was generated by an LLM (ChatGPT)

// Initializes the firebase functions and gives admin rights to reset values

const {onSchedule} = require("firebase-functions/v2/scheduler");
const admin = require("firebase-admin");
const logger = require("firebase-functions/logger");

admin.initializeApp();

// Function that resets every monday at 00:00 Paris time
exports.weeklyReset = onSchedule(
    "0 0 * * MON",
    {timeZone: "Europe/Paris"},
    async (event) => {
      try {
        const db = admin.firestore();
        const usersSnapshot = await db.collection("profiles").get();

        for (const userDoc of usersSnapshot.docs) {
          const userData = userDoc.data();
          const userId = userDoc.id;

          const friends = userData.friends || []; // array of userIDs

          if (friends.length < 3) continue;

          // ---- Fetch friends weeklyPoints IN BATCHES ----
          const friendChunks = [];
          for (let i = 0; i < friends.length; i += 10) {
            friendChunks.push(friends.slice(i, i + 10));
          }
          const friendDataList = [];

          for (const chunk of friendChunks) {
            const friendsSnapshot = await db
                .collection("profiles")
                .where(admin.firestore.FieldPath.documentId(), "in", chunk)
                .get();

            friendsSnapshot.forEach((doc) => {
              friendDataList.push({
                userId: doc.id,
                weeklyPoints: doc.data().weeklyPoints || 0.0,
              });
            });
          }

          // Add the user themselves to the ranking
          friendDataList.push({
            userId: userId,
            weeklyPoints: userData.weeklyPoints || 0.0,
          });

          // ---- Sort leaderboard ----
          friendDataList.sort((a, b) => b.weeklyPoints - a.weeklyPoints);

          // ---- Find user rank ----
          let currentRank = 0;
          let lastPoints = null;
          let ranks = [];

          for (let i = 0; i < friendDataList.length; i++) {
            const user = friendDataList[i];

            if (lastPoints !== null && user.weeklyPoints < lastPoints) {
              // points decreased -> next rank
              currentRank += 1;
            }

            ranks.push(currentRank);
            lastPoints = user.weeklyPoints;
          }

          // ---- If rank = 0 / 1 / 2 -> Give reward ----
          const index = friendDataList.findIndex((u) => u.userId === userId);
          const rank = ranks[index]

          const userRef = db.collection("profiles").doc(userId);
          if (rank == 0) {
            const achievementRef = db.collection("points").doc();
            const batch = db.batch();

            batch.set(achievementRef, {
              userId: userId,
              rank: "first",
              obtained: 100.0,
              dateObtained: admin.firestore.Timestamp.now(),
              reason: "Leaderboard",
            });

            batch.update(userRef, {
              focusPoints: admin.firestore.FieldValue.increment(100.0)
            });

            await batch.commit();
            logger.info("Achievement added and user points updated!");
          } else if (rank == 1) {
            const achievementRef = db.collection("points").doc();
            const batch = db.batch();

            batch.set(achievementRef, {
              userId: userId,
              rank: "second",
              obtained: 75.0,
              dateObtained: admin.firestore.Timestamp.now(),
              reason: "Leaderboard",
            });

            batch.update(userRef, {
              focusPoints: admin.firestore.FieldValue.increment(75.0)
            });

            await batch.commit();
            logger.info("Achievement added and user points updated!");
          } else if (rank == 2) {
            const achievementRef = db.collection("points").doc();
            const batch = db.batch();

            batch.set(achievementRef, {
              userId: userId,
              rank: "third",
              obtained: 50.0,
              dateObtained: admin.firestore.Timestamp.now(),
              reason: "Leaderboard",
            });

            batch.update(userRef, {
              focusPoints: admin.firestore.FieldValue.increment(50.0)
            });

            await batch.commit();
            logger.info("Achievement added and user points updated!");
          }
        }

        const batch = db.batch();
        usersSnapshot.forEach((doc) => {
          batch.update(doc.ref, {weeklyPoints: 0.0});
        });

        await batch.commit();

        logger.info("Weekly reset executed successfully");
      } catch (err) {
        logger.error("Weekly reset failed", err);
      }
    },
);
