package com.android.gatherly.model.notification

import com.google.firebase.Timestamp

// This file contains code generated by an LLM (Claude.ai).

/**
 * Represents the different types of in-app [Notification].
 *
 * Each [NotificationType] corresponds to a specific user action or system event that should be
 * communicated to the user.
 */
enum class NotificationType {
  /** A user has sent a friend request to the recipient. */
  FRIEND_REQUEST,
  /** A previously sent friend request has been accepted. */
  FRIEND_ACCEPTED,
  /** A previously sent friend request has been rejected. */
  FRIEND_REJECTED,
  /** A user removed the recipient from his friends. */
  REMOVE_FRIEND,
  /** A previously sent friend request has been cancelled by the sender. */
  FRIEND_REQUEST_CANCELLED,
  /** A reminder notification for a recipient's todo's approaching deadline. */
  TODO_REMINDER,
  /** A reminder notification for an upcoming event the recipient participates in. */
  EVENT_REMINDER,
  /** The recipient has been added to a group. */
  GROUP_ADDED,
  /** The recipient has been added as a participant to an event. */
  EVENT_PARTICIPATION
}

/**
 * Represents a single [Notification] item within the app.
 *
 * @property id Unique identifier of the notification.
 * @property type The type of notification.
 * @property emissionTime Timestamp indicating when the notification was created.
 * @property senderId UID of the user who triggered the notification, if applicable. This may be
 *   null for system-generated notifications.
 * @property relatedEntityId Identifier of the related entity (e.g. event ID, todo ID, group ID), if
 *   applicable.
 * @property recipientId UID of the user receiving the notification.
 * @property wasRead Whether the notification has been marked as read by the recipient.
 */
data class Notification(
    val id: String,
    val type: NotificationType,
    val emissionTime: Timestamp,
    val senderId: String?,
    val relatedEntityId: String?,
    val recipientId: String,
    val wasRead: Boolean
)
