package com.android.gatherly.model.notification

import com.google.firebase.Timestamp

// This file contains code generated by an LLM (Claude.ai).

/** Represents the type of a [Notification]. */
enum class NotificationType {
  FRIEND_REQUEST,
  TODO_REMINDER,
  EVENT_REMINDER
}

/** Represents a single [Notification] item within the app. */
data class Notification(
    val id: String,
    val type: NotificationType,
    val emissionTime: Timestamp,
    val senderId: String?,
    val relatedEntityId: String?,
    val recipientId: String,
    val wasRead: Boolean
)
