package com.android.gatherly.model.notification

// This file contains code generated by an LLM (Claude.ai).

interface NotificationsRepository {
  /** Returns a new unique ID for a notification. */
  fun getNewId(): String

  /** Returns a list of all notifications for the specified user, ordered by emission time. */
  suspend fun getUserNotifications(userId: String): List<Notification>

  /** Returns the notification with the given ID, or throws NoSuchElementException if not found. */
  suspend fun getNotification(notificationId: String): Notification

  /** Adds a new notification to the repository. */
  suspend fun addNotification(notification: Notification)

  /** Marks the specified notification as read. */
  suspend fun markAsRead(notificationId: String)

  /** Deletes the specified notification. */
  suspend fun deleteNotification(notificationId: String)
}
