package com.android.gatherly.model.notification

// This file contains code generated by an LLM (Claude.ai).

/** Repository interface for managing user notifications. */
interface NotificationsRepository {

  /**
   * Generates a new unique identifier for a notification.
   *
   * @return A unique notification ID.
   */
  fun getNewId(): String

  /**
   * Retrieves all notifications addressed to the given user.
   *
   * Notifications are returned in chronological order (oldest first), based on their
   * [Notification.emissionTime].
   *
   * @param userId UID of the user whose notifications should be retrieved.
   * @return A list of notifications for the specified user.
   */
  suspend fun getUserNotifications(userId: String): List<Notification>

  /**
   * Retrieves a notification by its unique identifier.
   *
   * @param notificationId The ID of the notification to retrieve.
   * @return The corresponding [Notification].
   * @throws NoSuchElementException if no notification with the given ID exists.
   */
  suspend fun getNotification(notificationId: String): Notification

  /**
   * Adds a new notification to the repository.
   *
   * @param notification The notification to add.
   */
  suspend fun addNotification(notification: Notification)

  /**
   * Marks the specified notification as read.
   *
   * @param notificationId The ID of the notification to mark as read.
   * @throws NoSuchElementException if the notification does not exist.
   */
  suspend fun markAsRead(notificationId: String)

  /**
   * Deletes a notification from the repository.
   *
   * @param notificationId The ID of the notification to delete.
   * @throws NoSuchElementException if the notification does not exist.
   */
  suspend fun deleteNotification(notificationId: String)
}
