package com.android.gatherly.ui.todo

import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextFieldColors
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.TextRange
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.input.TextFieldValue
import com.android.gatherly.R

// This composable contains code generated by an LLM.

/**
 * A reusable composable that displays a date input field with a numerical keyboard. This component
 * is designed to format the date input as "dd/MM/yyyy" while the user types.
 *
 * @param onDateChanged Callback triggered whenever the user edits the date.
 * @param dueDateError An optional error message to display below the input field.
 * @param textFieldColors The colors to be used for the text field.
 * @param testTagInput The test tag used for the date input field.
 * @param testTagErrorMessage The test tag used for the error message text.
 */
@Composable
fun DateInputField(
    initialDate: String = "",
    onDateChanged: (String) -> Unit = {},
    dueDateError: String? = null,
    textFieldColors: TextFieldColors,
    testTagInput: String,
    testTagErrorMessage: String,
) {
  var dateFieldValue by remember { mutableStateOf(TextFieldValue("")) }
  dateFieldValue = dateFieldValue.copy(text = initialDate)
  OutlinedTextField(
      value = dateFieldValue,
      onValueChange = { newValue ->
        val oldText = dateFieldValue.text
        val newText = newValue.text

        // Detect if user is deleting (backspace)
        val isDeleting = newText.length < oldText.length

        val formatted = formatDateInput(newText)

        // Calculate new cursor position
        val newCursorPos =
            when {
              isDeleting -> newValue.selection.start.coerceAtMost(formatted.length)
              else -> formatted.length // keep cursor at end when typing
            }

        dateFieldValue = newValue.copy(text = formatted, selection = TextRange(newCursorPos))

        onDateChanged(formatted)
      },
      label = { Text(stringResource(R.string.todos_date_field_label)) },
      placeholder = { Text(stringResource(R.string.todos_date_field_placeholder)) },
      isError = dueDateError != null,
      supportingText = {
        dueDateError?.let { Text(it, modifier = Modifier.testTag(testTagErrorMessage)) }
      },
      colors = textFieldColors,
      keyboardOptions =
          KeyboardOptions(keyboardType = KeyboardType.Number, imeAction = ImeAction.Next),
      modifier = Modifier.fillMaxWidth().testTag(testTagInput),
  )
}

private fun formatDateInput(input: String): String {
  // Remove any non-digit characters
  val digits = input.filter { it.isDigit() }.take(8) // Limit to ddMMyyyy
  return buildString {
    for (i in digits.indices) {
      append(digits[i])
      if (i == 1 || i == 3) append('/')
    }
  }
}
