package com.android.gatherly.ui.todo

import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextFieldColors
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.TextRange
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.input.TextFieldValue
import com.android.gatherly.R

// This composable contains code generated by an LLM.

/**
 * A reusable composable that displays a time input field with a numerical keyboard. This component
 * is designed to format the time input as "HH:mm" while the user types.
 *
 * @param onTimeChanged Callback triggered whenever the user edits the time.
 * @param dueTimeError An optional error message to display below the input field.
 * @param textFieldColors The colors to be used for the text field.
 * @param testTagInput The test tag used for the time input field.
 * @param testTagErrorMessage The test tag used for the error message text.
 */
@Composable
fun TimeInputField(
    initialTime: String = "",
    onTimeChanged: (String) -> Unit = {},
    dueTimeError: String? = null,
    textFieldColors: TextFieldColors,
    testTagInput: String,
    testTagErrorMessage: String,
) {
  var timeFieldValue by remember { mutableStateOf(TextFieldValue("")) }
  timeFieldValue = timeFieldValue.copy(text = initialTime)
  OutlinedTextField(
      value = timeFieldValue,
      onValueChange = { newValue ->
        val oldText = timeFieldValue.text
        val newText = newValue.text

        // Detect if user is deleting (backspace)
        val isDeleting = newText.length < oldText.length

        val formatted = formatTimeInput(newText)

        // Calculate new cursor position
        val newCursorPos =
            when {
              isDeleting -> newValue.selection.start.coerceAtMost(formatted.length)
              else -> formatted.length // keep cursor at end when typing
            }

        timeFieldValue = newValue.copy(text = formatted, selection = TextRange(newCursorPos))

        onTimeChanged(formatted)
      },
      label = { Text(stringResource(R.string.todos_time_field_label)) },
      placeholder = { Text(stringResource(R.string.todos_time_field_placeholder)) },
      isError = dueTimeError != null,
      supportingText = {
        dueTimeError?.let { Text(it, modifier = Modifier.testTag(testTagErrorMessage)) }
      },
      colors = textFieldColors,
      keyboardOptions =
          KeyboardOptions(keyboardType = KeyboardType.Number, imeAction = ImeAction.Next),
      modifier = Modifier.fillMaxWidth().testTag(testTagInput),
  )
}

private fun formatTimeInput(input: String): String {
  // Remove any non-digit characters
  val digits = input.filter { it.isDigit() }.take(4) // Limit to HHmm
  return buildString {
    for (i in digits.indices) {
      append(digits[i])
      // Add colon after hour (2 digits)
      if (i == 1) append(':')
    }
  }
}
