package com.android.gatherly.utils

import androidx.compose.ui.graphics.painter.Painter
import androidx.compose.ui.test.junit4.createComposeRule
import coil.compose.AsyncImagePainter
import kotlin.test.assertTrue
import org.junit.Rule
import org.junit.Test

// part of this file contain code generated by ChatGPT

class ProfilePictureUtilsTest {

  @get:Rule val composeTestRule = createComposeRule()

  /** Test that profilePicturePainter returns an AsyncImagePainter when a URL is provided */
  @Test
  fun profile_picture_painter_returns_asyncImagePainter_for_valid_url() {
    var painter: Painter? = null

    composeTestRule.setContent { painter = profilePicturePainter("https://example.com/pic.jpg") }
    assertTrue(painter is AsyncImagePainter)
  }

  /** Test that profilePicturePainter returns the placeholder painter when URL is null */
  @Test
  fun profile_picture_painter_returns_placeholder_for_null_url() {
    var painter: Painter? = null

    composeTestRule.setContent { painter = profilePicturePainter(null) }

    assertTrue(painter !is AsyncImagePainter)
  }

  /** Test that profilePicturePainter returns the placeholder painter when URL is empty */
  @Test
  fun profile_picture_painter_returns_placeholder_for_empty_url() {
    var painter: Painter? = null

    composeTestRule.setContent { painter = profilePicturePainter("") }

    assertTrue(painter !is AsyncImagePainter)
  }
}
