package com.android.gatherly.model.group

// This file contains code generated by an LLM (GitHub Copilot, Claude.ai).

/**
 * Represents a single [Group] item within the app.
 *
 * @property gid The unique identifier for the group
 * @property creatorId The user ID of the group creator
 * @property name The name of the group
 * @property description Optional additional description of the group
 * @property memberIds List of user IDs who are members of the group
 * @property adminIds List of user IDs who have administrative privileges
 */
data class Group(
    val gid: String = "",
    val creatorId: String = "",
    val name: String = "",
    val description: String? = null,
    val memberIds: List<String> = emptyList(), // contains userIds
    val adminIds: List<String> = emptyList() // contains userIds
)
