package com.android.gatherly.model.group

import com.google.firebase.Firebase
import com.google.firebase.firestore.firestore

// Portions of the code in this file are copy-pasted from the Bootcamp solution provided by the
// SwEnt staff.

// This file contains code generated by an LLM (Claude.ai).

/**
 * Provides a single instance of the repository in the app. `repository` is mutable for testing
 * purposes.
 */
object GroupsRepositoryProvider {
  private val _repository: GroupsRepository by lazy {
    GroupsRepositoryFirestore(Firebase.firestore)
  }

  var repository: GroupsRepository = _repository
}
