package com.android.gatherly.model.group

// This file contains code generated by an LLM (GitHub Copilot, Claude.ai).

/** Represents a single [Group] item within the app. */
data class Group(
    val gid: String,
    val name: String,
    val description: String? = null,
    val memberIds: List<String>, // contains userIds
    val adminIds: List<String> // contains userIds
)
