package com.android.gatherly.viewmodel.friends

import com.android.gatherly.model.badge.BadgeType
import com.android.gatherly.model.profile.Profile
import com.android.gatherly.model.profile.ProfileRepository
import com.android.gatherly.model.profile.ProfileStatus
import com.android.gatherly.model.profile.UserStatusSource

// This file contains code generated by an LLM (Claude.ai).

/**
 * Test data fixture for FriendsViewModel tests.
 *
 * Provides:
 * - User ID constants for test users
 * - Username constants for test users
 * - Profile fixtures representing different friend relationships:
 *     - [userA] and [userB]: Mutual friends
 *     - [userC]: User with no friends
 *     - [anon]: Anonymous user profile
 * - [createErrorThrowingProfileRepository]: Factory function for mock repository that throws
 *   exceptions on getFriendsAndNonFriendsUsernames to test error handling
 */
object FriendsViewModelTestsData {

  const val USER_A_ID = "A"
  const val USER_A_USERNAME = "alice"
  const val USER_B_ID = "B"
  const val USER_B_USERNAME = "bob"
  const val USER_C_ID = "C"
  const val USER_C_USERNAME = "charlie"

  val userA: Profile =
      Profile(
          uid = USER_A_ID,
          username = "alice",
          name = "ProfileA",
          focusSessionIds = emptyList(),
          participatingEventIds = emptyList(),
          groupIds = emptyList(),
          friendUids = listOf(USER_B_ID),
          profilePicture = "profileA.png")

  val userB: Profile =
      Profile(
          uid = USER_B_ID,
          username = "bob",
          name = "ProfileB",
          focusSessionIds = emptyList(),
          participatingEventIds = emptyList(),
          groupIds = emptyList(),
          friendUids = listOf(USER_A_ID),
          profilePicture = "profileB.png")

  val userC: Profile =
      Profile(
          uid = USER_C_ID,
          username = "charlie",
          name = "ProfileC",
          focusSessionIds = emptyList(),
          participatingEventIds = emptyList(),
          groupIds = emptyList(),
          friendUids = emptyList(),
          profilePicture = "profileC.png")

  val anon: Profile =
      Profile(
          uid = "",
          username = "",
          name = "",
          focusSessionIds = emptyList(),
          participatingEventIds = emptyList(),
          groupIds = emptyList(),
          friendUids = emptyList(),
          profilePicture = "anon.png")
  /**
   * Creates a mock ProfileRepository that throws an exception when getFriendsAndNonFriendsUsernames
   * is called. Used to test error handling in FriendsViewModel.
   *
   * @param errorMessage The error message to include in the thrown exception
   * @return A ProfileRepository that simulates a connection failure
   */
  fun createErrorThrowingProfileRepository(errorMessage: String): ProfileRepository =
      object : ProfileRepository {
        override suspend fun getFriendsAndNonFriendsUsernames(
            currentUserId: String
        ): com.android.gatherly.model.friends.Friends {
          throw Exception(errorMessage)
        }

        override suspend fun getProfileByUid(uid: String): Profile? = null

        override suspend fun updateProfile(profile: Profile) {}

        override suspend fun deleteProfile(uid: String) {}

        override suspend fun isUidRegistered(uid: String): Boolean = false

        override suspend fun searchProfilesByNamePrefix(prefix: String): List<Profile> = emptyList()

        override suspend fun isUsernameAvailable(username: String): Boolean = false

        override suspend fun registerUsername(uid: String, username: String): Boolean = false

        override suspend fun updateUsername(
            uid: String,
            oldUsername: String?,
            newUsername: String
        ): Boolean = false

        override suspend fun updateProfilePic(uid: String, uri: android.net.Uri): String = ""

        override suspend fun getProfileByUsername(username: String): Profile? = null

        override suspend fun searchProfilesByUsernamePrefix(
            prefix: String,
            limit: Int
        ): List<Profile> = emptyList()

        override suspend fun initProfileIfMissing(uid: String, defaultPhotoUrl: String): Boolean =
            false

        override suspend fun addProfile(profile: Profile) {}

        override suspend fun getListNoFriends(currentUserId: String): List<String> = emptyList()

        override suspend fun addFriend(friend: String, currentUserId: String) {}

        override suspend fun addPendingSentFriendUid(currentUserId: String, targetUid: String) {}

        override suspend fun removePendingSentFriendUid(currentUserId: String, targetUid: String) {}

        override suspend fun updateStatus(
            uid: String,
            status: ProfileStatus,
            source: UserStatusSource
        ) {}

        override suspend fun createEvent(eventId: String, currentUserId: String) {}

        override suspend fun deleteEvent(eventId: String, currentUserId: String) {}

        override suspend fun participateEvent(eventId: String, currentUserId: String) {}

        override suspend fun deleteFriend(friend: String, currentUserId: String) {}

        override suspend fun allParticipateEvent(eventId: String, participants: List<String>) {}

        override suspend fun unregisterEvent(eventId: String, currentUserId: String) {}

        override suspend fun allUnregisterEvent(eventId: String, participants: List<String>) {}

        override suspend fun addBadge(uid: String, badgeId: String) {}

        override suspend fun incrementBadge(uid: String, type: BadgeType): String? {
          return null
        }

        override suspend fun deleteUserProfile(uid: String) {}

        override suspend fun updateFocusPoints(
            uid: String,
            points: Double,
            addToLeaderboard: Boolean
        ) {}
      }
}
