package com.android.gatherly.model.points

import com.google.firebase.Timestamp

// This file contains code generated by an LLM (ChatGPT).

/**
 * This data class is used to represent an instance of a user obtaining points. It is useful mainly
 * to display the history of points acquisition to the user.
 *
 * @property userId The identifier of the user which obtained the points
 * @property obtained The number of points obtained (can be non integer)
 * @property reason The reason the points were obtained
 * @property dateObtained The date and time at which the points were obtained
 */
data class Points(
    val userId: String = "",
    val obtained: Double = 0.0,
    val reason: PointsType,
    val dateObtained: Timestamp = Timestamp.now()
)

/**
 * This class represents a reason for which points were obtained. This is for the user to understand
 * why they obtained points. Depending on the reason, different parameters are needed to construct
 * the string that will be displayed to the user. This can be augmented later if we decide to add
 * more ways to obtain points.
 */
sealed class PointsType {
  /**
   * The user used the focus timer
   *
   * @param minutes The number of minutes for which the user focused.
   */
  data class Timer(val minutes: Int) : PointsType()

  /**
   * The user obtained a badge
   *
   * @param badgeName The name of the badge the user obtained (this implementation can change
   *   depending on the implementation of the badges)
   */
  data class Badge(val badgeName: String) : PointsType()

  /**
   * The user was in the top three in their friends leaderboard
   *
   * @param rank The rank they obtained in their leaderboard (this implementation can change
   *   depending on the implementation of the leaderboard)
   */
  data class Leaderboard(val rank: String) : PointsType()
}

/** Transforms the [PointsType] to a string displayable to the user */
fun pointsTypeToString(type: PointsType): String {
  return when (type) {
    is PointsType.Timer -> "Focused for ${type.minutes} minutes"
    is PointsType.Badge -> "Obtained the ${type.badgeName} badge"
    is PointsType.Leaderboard -> "Reached ${type.rank} on your friends leaderboard"
  }
}
