package com.android.gatherly.viewmodel.groups.overview

import com.android.gatherly.model.group.Group

// This file contains code generated by an LLM (Claude.ai).

/**
 * Contains test data fixtures for [com.android.gatherly.ui.groups.GroupsOverviewViewModel] tests.
 *
 * Provides sample groups with various configurations for testing different scenarios.
 */
object GroupsOverviewViewModelTestData {

  const val TEST_USER_ID = "testUser"
  const val OTHER_USER_ID = "otherUser"
  const val FRIEND_USER_ID = "friendUser"

  val userGroup1 =
      Group(
          gid = "group1",
          creatorId = TEST_USER_ID,
          name = "Study Group",
          description = "CS students study group",
          memberIds = listOf(TEST_USER_ID, FRIEND_USER_ID),
          adminIds = listOf(TEST_USER_ID))

  val userGroup2 =
      Group(
          gid = "group2",
          creatorId = OTHER_USER_ID,
          name = "Running Club",
          description = "Weekly running meetups",
          memberIds = listOf(TEST_USER_ID, OTHER_USER_ID, FRIEND_USER_ID),
          adminIds = listOf(OTHER_USER_ID, TEST_USER_ID))

  val userGroup3 =
      Group(
          gid = "group3",
          creatorId = TEST_USER_ID,
          name = "Project Team",
          description = null,
          memberIds = listOf(TEST_USER_ID),
          adminIds = listOf(TEST_USER_ID))

  val otherUserGroup =
      Group(
          gid = "group4",
          creatorId = OTHER_USER_ID,
          name = "Other Group",
          description = "Group where testUser is not a member",
          memberIds = listOf(OTHER_USER_ID, FRIEND_USER_ID),
          adminIds = listOf(OTHER_USER_ID))

  /** All groups where TEST_USER_ID is a member */
  val testUserGroups = listOf(userGroup1, userGroup2, userGroup3)

  /** All groups in the system */
  val allGroups = listOf(userGroup1, userGroup2, userGroup3, otherUserGroup)
}
