package com.android.gatherly.viewmodel.groups.add

import com.android.gatherly.model.profile.Profile

// This file contains code generated by an LLM (Claude.ai).

/**
 * Contains test data fixtures for [com.android.gatherly.ui.groups.AddGroupViewModel] tests.
 *
 * Provides sample user profiles for testing friend selection and group creation scenarios.
 */
object AddGroupViewModelTestData {

  /** Test user ID representing the current logged-in user. */
  const val TEST_USER_ID = "test-user-123"

  /** Sample friend profile 1. */
  val FRIEND_ALICE =
      Profile(uid = "friend-alice", username = "alice_a", name = "Alice", friendUids = emptyList())

  /** Sample friend profile 2. */
  val FRIEND_BOB =
      Profile(uid = "friend-bob", username = "bob_b", name = "Bob", friendUids = emptyList())

  /** Sample friend profile 3. */
  val FRIEND_CHARLIE =
      Profile(
          uid = "friend-charlie",
          username = "charlie_c",
          name = "Charlie",
          friendUids = emptyList())

  /** The current user's profile with a friends list. */
  val CURRENT_USER_PROFILE =
      Profile(
          uid = TEST_USER_ID,
          username = "testuser",
          name = "Test User",
          friendUids = listOf(FRIEND_ALICE.uid, FRIEND_BOB.uid, FRIEND_CHARLIE.uid))

  /** List of all friend profiles for easy access. */
  val ALL_FRIENDS = listOf(FRIEND_ALICE, FRIEND_BOB, FRIEND_CHARLIE)
}
