package com.android.gatherly.viewmodel

import com.android.gatherly.model.group.Group
import com.android.gatherly.model.group.GroupsRepository

// This file contains code that was generated by an LLM (Claude.ai).

/**
 * An in-memory implementation of [GroupsRepository] for use in unit tests.
 *
 * This class stores groups in a mutable map and allows adding, retrieving, updating, and removing
 * groups without accessing any real database or network. Useful for testing
 * GroupsOverviewViewModel, AddGroupViewModel, EditGroupViewModel, or other components that depend
 * on [GroupsRepository].
 *
 * @param currentUserId The user ID to use for operations that check current user (defaults to
 *   "testUser")
 */
class FakeGroupsRepositoryLocal(private val currentUserId: String = "testUser") : GroupsRepository {
  private val groups = mutableMapOf<String, Group>()
  private var idCounter = 0

  /** If true, addGroup will throw an exception (for testing error handling) */
  var shouldThrowOnAddGroup = false
  var shouldThrowOnEditGroup = false

  override fun getNewId(): String {
    return "testGroupId${idCounter++}"
  }

  override suspend fun getAllGroups(): List<Group> {
    return groups.values.toList()
  }

  override suspend fun getUserGroups(): List<Group> {
    return groups.values.filter { group -> currentUserId in group.memberIds }
  }

  override suspend fun getGroupByName(groupName: String): Group {
    return groups.values.firstOrNull { it.name.equals(groupName, ignoreCase = true) }
        ?: throw NoSuchElementException("Group with name='$groupName' not found")
  }

  override suspend fun getGroup(groupId: String): Group {
    return groups[groupId] ?: throw NoSuchElementException("Group with id=$groupId not found")
  }

  override suspend fun addGroup(group: Group) {
    if (shouldThrowOnAddGroup) {
      throw Exception("Test error")
    }
    groups[group.gid] = group
  }

  override suspend fun editGroup(groupId: String, newValue: Group) {
    if (shouldThrowOnEditGroup) {
      throw Exception("Test error")
    }
    val existing = getGroup(groupId)
    if (currentUserId !in existing.adminIds) {
      throw SecurityException("Only admins can edit this group")
    }
    // Preserve the original creatorId
    val updated = newValue.copy(creatorId = existing.creatorId)
    groups[groupId] = updated
  }

  override suspend fun deleteGroup(groupId: String) {
    val existing = getGroup(groupId)
    if (currentUserId !in existing.adminIds) {
      throw SecurityException("Only admins can delete this group")
    }
    groups.remove(groupId)
  }

  override suspend fun addMember(groupId: String, userId: String) {
    val group = getGroup(groupId)
    if (userId !in group.memberIds) {
      groups[groupId] = group.copy(memberIds = group.memberIds + userId)
    }
  }

  override suspend fun removeMember(groupId: String, userId: String) {
    val group = getGroup(groupId)
    val updatedMembers = group.memberIds.filter { it != userId }
    val updatedAdmins = group.adminIds.filter { it != userId }

    if (updatedAdmins.isEmpty()) {
      throw IllegalStateException("Cannot remove the last admin")
    }

    groups[groupId] = group.copy(memberIds = updatedMembers, adminIds = updatedAdmins)
  }

  override suspend fun addAdmin(groupId: String, userId: String) {
    val group = getGroup(groupId)
    if (userId !in group.memberIds) {
      throw IllegalStateException("User must be a member to become admin")
    }
    if (userId !in group.adminIds) {
      groups[groupId] = group.copy(adminIds = group.adminIds + userId)
    }
  }

  override suspend fun removeAdmin(groupId: String, userId: String) {
    val group = getGroup(groupId)
    val updatedAdmins = group.adminIds.filter { it != userId }

    if (updatedAdmins.isEmpty()) {
      throw IllegalStateException("Cannot remove the last admin")
    }

    groups[groupId] = group.copy(adminIds = updatedAdmins)
  }

  /** Utility method for tests: add multiple groups at once */
  fun addGroups(groupList: List<Group>) {
    groupList.forEach { groups[it.gid] = it }
  }

  /** Utility method for tests: clear all groups */
  fun clear() {
    groups.clear()
  }
}
