package com.android.gatherly.model.notification

import com.google.firebase.Timestamp

// This file contains code generated by an LLM (Claude.ai, GitHub Copilot).

object NotificationsLocalRepositoryTestData {
  /**
   * Helper function to create a sample notification for testing.
   *
   * @param id The unique identifier for the notification.
   * @param type The type of the notification.
   * @param emissionTime The time the notification was emitted.
   * @param senderId The ID of the sender (optional).
   * @param relatedEntityId The ID of the related entity (optional).
   * @param recipientId The ID of the recipient.
   * @param wasRead Whether the notification has been read (default is false).
   * @return A [Notification] object with the specified parameters.
   */
  fun createSampleNotification(
      id: String,
      type: NotificationType,
      emissionTime: Timestamp,
      senderId: String? = null,
      relatedEntityId: String? = null,
      recipientId: String,
      wasRead: Boolean = false
  ): Notification {
    return Notification(
        id = id,
        type = type,
        emissionTime = emissionTime,
        senderId = senderId,
        relatedEntityId = relatedEntityId,
        recipientId = recipientId,
        wasRead = wasRead)
  }

  /** Function to create timestamps for testing purposes. */
  fun createTimestamp(seconds: Long, nanoseconds: Int = 0): Timestamp {
    return Timestamp(seconds, nanoseconds)
  }

  val friendRequest1 =
      createSampleNotification(
          id = "1",
          type = NotificationType.FRIEND_REQUEST,
          emissionTime = createTimestamp(1000, 0),
          senderId = "userA",
          recipientId = "userB")

  val friendRequest2 =
      createSampleNotification(
          id = "2",
          type = NotificationType.FRIEND_REQUEST,
          emissionTime = createTimestamp(2000, 0),
          senderId = "userC",
          recipientId = "userB")

  val friendRequest3 =
      createSampleNotification(
          id = "3",
          type = NotificationType.FRIEND_REQUEST,
          emissionTime = createTimestamp(3000, 0),
          senderId = "userD",
          recipientId = "userE")

  val todoReminder1 =
      createSampleNotification(
          id = "4",
          type = NotificationType.TODO_REMINDER,
          emissionTime = createTimestamp(4000, 0),
          relatedEntityId = "todo1",
          recipientId = "userA")

  val todoReminder2 =
      createSampleNotification(
          id = "5",
          type = NotificationType.TODO_REMINDER,
          emissionTime = createTimestamp(5000, 0),
          relatedEntityId = "todo2",
          recipientId = "userB")

  val todoReminder3 =
      createSampleNotification(
          id = "6",
          type = NotificationType.TODO_REMINDER,
          emissionTime = createTimestamp(6000, 0),
          relatedEntityId = "todo3",
          recipientId = "userC")

  val eventReminder1 =
      createSampleNotification(
          id = "7",
          type = NotificationType.EVENT_REMINDER,
          emissionTime = createTimestamp(7000, 0),
          relatedEntityId = "event1",
          recipientId = "userA")
  val eventReminder2 =
      createSampleNotification(
          id = "8",
          type = NotificationType.EVENT_REMINDER,
          emissionTime = createTimestamp(8000, 0),
          relatedEntityId = "event2",
          recipientId = "userB")

  val eventReminder3 =
      createSampleNotification(
          id = "9",
          type = NotificationType.EVENT_REMINDER,
          emissionTime = createTimestamp(9000, 0),
          relatedEntityId = "event3",
          recipientId = "userC")

  val friendRequests = listOf(friendRequest1, friendRequest2, friendRequest3)
  val todoReminders = listOf(todoReminder1, todoReminder2, todoReminder3)
  val eventReminders = listOf(eventReminder1, eventReminder2, eventReminder3)
}
