package com.android.gatherly.ui.groups

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.android.gatherly.model.group.Group
import com.android.gatherly.model.group.GroupsRepository
import com.android.gatherly.model.group.GroupsRepositoryFirestore
import com.android.gatherly.model.profile.ProfileRepository
import com.android.gatherly.model.profile.ProfileRepositoryProvider
import com.google.firebase.Firebase
import com.google.firebase.firestore.firestore
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

// Portions of the code in this file are copy-pasted from the Bootcamp solution provided by the
// SwEnt staff.

// This file contains code generated by an LLM (Claude.ai).

/**
 * Represents the UI state for the Groups Overview screen.
 *
 * @property groups A list of `Group` items to be displayed in the Overview screen. Defaults to an
 *   empty list if no items are available.
 */
data class GroupsOverviewUIState(
    val groups: List<Group> = emptyList(),
    val profilePics: List<List<String>> = emptyList<List<String>>(),
    val errorMsg: String? = null,
    val isLoading: Boolean = true
)

/**
 * ViewModel for the Groups Overview screen.
 *
 * Responsible for managing the UI state, by fetching and providing Group items via the
 * [GroupsRepository].
 *
 * @property groupsRepository The repository used to fetch and manage Group items.
 */
class GroupsOverviewViewModel(
    private val groupsRepository: GroupsRepository = GroupsRepositoryFirestore(Firebase.firestore),
    private val profileRepository: ProfileRepository = ProfileRepositoryProvider.repository
) : ViewModel() {

  private val _uiState = MutableStateFlow(GroupsOverviewUIState())
  val uiState: StateFlow<GroupsOverviewUIState> = _uiState.asStateFlow()

  init {
    getUserGroups()
  }

  /** Refreshes the UI state by fetching all Group items from the repository. */
  fun refreshUIState() {
    getUserGroups()
  }

  /** Fetches user's groups from the repository and updates the UI state. */
  private fun getUserGroups() {
    viewModelScope.launch {
      _uiState.value = _uiState.value.copy(isLoading = true, errorMsg = null)
      try {
        val groups = groupsRepository.getUserGroups()

        val maxProfilePicsToDisplay = 3

        for (group in groups) {

          // The list of profile picture urls of this group (at most 3 to display)
          val groupProfilePics = mutableListOf<String>()

          for (i in 0 until minOf(maxProfilePicsToDisplay, group.memberIds.size)) {
            val profile = profileRepository.getProfileByUid(group.memberIds[i])!!
            groupProfilePics.add(profile.profilePicture)
          }
          _uiState.value =
              _uiState.value.copy(
                  profilePics = _uiState.value.profilePics + listOf(groupProfilePics.toList()))
        }
        _uiState.value = _uiState.value.copy(groups = groups, isLoading = false)
      } catch (e: Exception) {
        _uiState.value =
            _uiState.value.copy(groups = emptyList(), errorMsg = e.message, isLoading = false)
      }
    }
  }

  /** Resets the error message to null once it was displayed */
  fun resetErrorMessage() {
    _uiState.value = _uiState.value.copy(errorMsg = null)
  }
}
