package com.android.gatherly

import kotlin.time.Duration
import kotlin.time.Duration.Companion.seconds
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.test.TestScope
import kotlinx.coroutines.test.UnconfinedTestDispatcher
import kotlinx.coroutines.test.runTest

// This file contains code generated by an LLM (Claude.ai).

/**
 * Runs a test with an unconfined test dispatcher.
 *
 * @param timeout Maximum duration for the test (default: 60 seconds).
 * @param testBody The suspend function containing the test code to execute.
 */
@OptIn(ExperimentalCoroutinesApi::class)
fun runUnconfinedTest(timeout: Duration = 60.seconds, testBody: suspend TestScope.() -> Unit) =
    runTest(UnconfinedTestDispatcher(), timeout = timeout, testBody = testBody)
