package com.android.gatherly.viewmodel.homepage

import com.android.gatherly.model.event.Event
import com.android.gatherly.model.event.EventStatus
import com.android.gatherly.model.map.Location
import com.android.gatherly.model.profile.Profile
import com.android.gatherly.model.todo.ToDo
import com.android.gatherly.model.todo.ToDoStatus
import com.google.firebase.Timestamp
import java.text.SimpleDateFormat
import java.time.Instant
import java.time.temporal.ChronoUnit
import java.util.Date

// This file contains code generated by an LLM (Claude.ai).

/**
 * Contains test data fixtures for [com.android.gatherly.ui.homePage.HomePageViewModel] tests.
 *
 * Provides sample profiles, todos, events, and related data for testing various user scenarios
 * including users with friends, friendless users, and users with/without todos.
 */
object HomePageViewModelTestData {

  // User IDs
  const val CURRENT_USER_ID = ""
  const val FRIEND_1_ID = "1"
  const val FRIEND_2_ID = "2"
  const val FRIEND_3_ID = "3"
  const val FRIEND_4_ID = "4"

  // Profiles
  val friend1Profile =
      Profile(
          uid = FRIEND_1_ID,
          name = "Friend1",
          focusSessionIds = emptyList(),
          participatingEventIds = emptyList(),
          groupIds = emptyList(),
          friendUids = emptyList())

  val friend2Profile =
      Profile(
          uid = FRIEND_2_ID,
          name = "Friend2",
          focusSessionIds = emptyList(),
          participatingEventIds = emptyList(),
          groupIds = emptyList(),
          friendUids = emptyList())

  val friend3Profile =
      Profile(
          uid = FRIEND_3_ID,
          name = "Friend3",
          focusSessionIds = emptyList(),
          participatingEventIds = emptyList(),
          groupIds = emptyList(),
          friendUids = emptyList())

  val friend4Profile =
      Profile(
          uid = FRIEND_4_ID,
          name = "Friend4",
          focusSessionIds = emptyList(),
          participatingEventIds = emptyList(),
          groupIds = emptyList(),
          friendUids = emptyList())

  val currentProfile =
      Profile(
          uid = CURRENT_USER_ID,
          name = "Current",
          focusSessionIds = emptyList(),
          participatingEventIds = emptyList(),
          groupIds = emptyList(),
          friendUids = listOf(FRIEND_1_ID, FRIEND_2_ID, FRIEND_3_ID, FRIEND_4_ID))

  val friendlessProfile =
      Profile(
          uid = CURRENT_USER_ID,
          name = "Current",
          focusSessionIds = emptyList(),
          participatingEventIds = emptyList(),
          groupIds = emptyList(),
          friendUids = emptyList())

  /** All friends of the current user */
  val friendsList = listOf(friend1Profile, friend2Profile, friend3Profile, friend4Profile)

  // ToDos
  val todo1 =
      ToDo(
          uid = "todo1",
          name = "Todo1",
          description = "Desc",
          dueDate = Timestamp(1728000000, 0),
          dueTime = null,
          location =
              Location(latitude = 46.5186, longitude = 6.5661, name = "Rolex Learning Center"),
          status = ToDoStatus.ONGOING,
          ownerId = CURRENT_USER_ID)

  val todo2 =
      ToDo(
          uid = "todo2",
          name = "Todo2",
          description = "Desc",
          dueDate = Timestamp(1728000000, 0),
          dueTime = null,
          location = Location(latitude = 46.5190, longitude = 6.5668, name = "BC Building"),
          status = ToDoStatus.ONGOING,
          ownerId = CURRENT_USER_ID)

  val todo3 =
      ToDo(
          uid = "todo3",
          name = "Todo3",
          description = "Desc",
          dueDate = Timestamp(1728000000, 0),
          dueTime = null,
          location = null,
          status = ToDoStatus.ONGOING,
          ownerId = CURRENT_USER_ID)

  val todo4 =
      ToDo(
          uid = "todo4",
          name = "Todo4",
          description = "Desc",
          dueDate = Timestamp(1728000000, 0),
          dueTime = null,
          location = null,
          status = ToDoStatus.ONGOING,
          ownerId = CURRENT_USER_ID)

  /** ToDos with locations (displayable on map) */
  val displayableTodos = listOf(todo1, todo2)

  /** All upcoming todos */
  val upcomingTodos = listOf(todo1, todo2, todo3, todo4)

  // Events
  private val tomorrowTimestamp = Timestamp(Date.from(Instant.now().plus(1, ChronoUnit.DAYS)))
  private val startTime = Timestamp(SimpleDateFormat("HH:mm").parse("10:00")!!)
  private val endTime = Timestamp(SimpleDateFormat("HH:mm").parse("23:00")!!)

  val event1 =
      Event(
          id = "1",
          title = "Celebrate Christmas 2025",
          description = "Come celebrate christmas with us in a few months :)",
          creatorName = "Gatherly team",
          location = Location(latitude = 46.5190, longitude = 6.5668, name = "BC Building"),
          date = tomorrowTimestamp,
          startTime = startTime,
          endTime = endTime,
          creatorId = "gersende",
          participants =
              listOf("gersende", "colombe", "claire", "gab", "alessandro", "clau", "mohamed"),
          status = EventStatus.UPCOMING)

  val event2 =
      Event(
          id = "2",
          title = "Celebrate Christmas 2025",
          description = "Come celebrate christmas with us in a few months :)",
          creatorName = "Gatherly team",
          location = null,
          date = tomorrowTimestamp,
          startTime = startTime,
          endTime = endTime,
          creatorId = "gersende",
          participants =
              listOf("gersende", "colombe", "claire", "gab", "alessandro", "clau", "mohamed"),
          status = EventStatus.UPCOMING)

  /** Events with locations (displayable on map) */
  val displayableEvents = listOf(event1)
}
