package com.android.gatherly.ui.homepage

import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.assertIsNotDisplayed
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onNodeWithTag
import androidx.compose.ui.test.performClick
import com.android.gatherly.model.event.EventsLocalRepository
import com.android.gatherly.model.profile.Profile
import com.android.gatherly.model.profile.ProfileLocalRepository
import com.android.gatherly.model.profile.ProfileStatus
import com.android.gatherly.model.todo.ToDo
import com.android.gatherly.model.todo.ToDoStatus
import com.android.gatherly.model.todo.ToDosLocalRepository
import com.android.gatherly.ui.homePage.HomePageScreen
import com.android.gatherly.ui.homePage.HomePageScreenTestTags
import com.android.gatherly.ui.homePage.HomePageViewModel
import com.android.gatherly.ui.homePage.getFriendAvatarTestTag
import com.android.gatherly.ui.homePage.getFriendStatusTestTag
import com.android.gatherly.utils.MockitoUtils
import com.google.firebase.Timestamp
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.test.runTest
import org.junit.Before
import org.junit.Rule
import org.junit.Test

// Some parts of the code in this file are generated by ChatGPT. (e.g. documentation)

/**
 * UI tests for [HomePageScreen].
 *
 * These tests ensure that key components of the Home Page are displayed and interactable, including
 * tasks, buttons, map, and friends section.
 */
class HomePageScreenTest {

  val friend1 =
      Profile(
          uid = "homePageTests_friend1",
          name = "Alice",
          focusSessionIds = emptyList(),
          participatingEventIds = emptyList(),
          groupIds = emptyList(),
          friendUids = emptyList(),
          status = ProfileStatus.ONLINE)
  val friend2 =
      Profile(
          uid = "homePageTests_friend2",
          name = "Bob",
          focusSessionIds = emptyList(),
          participatingEventIds = emptyList(),
          groupIds = emptyList(),
          friendUids = emptyList(),
          status = ProfileStatus.FOCUSED)

  private var currentProfile: Profile =
      Profile(
          uid = "0+",
          name = "Current",
          focusSessionIds = emptyList(),
          participatingEventIds = emptyList(),
          groupIds = emptyList(),
          friendUids = listOf(friend1.uid, friend2.uid))

  @get:Rule val composeRule = createComposeRule()

  private lateinit var fakeViewModel: HomePageViewModel
  private lateinit var todosLocalRepo: ToDosLocalRepository
  private lateinit var eventsLocalRepo: EventsLocalRepository
  private lateinit var profileLocalRepo: ProfileLocalRepository
  private lateinit var mockitoUtils: MockitoUtils

  @Before
  fun setUp() {
    runTest {
      todosLocalRepo = ToDosLocalRepository()
      eventsLocalRepo = EventsLocalRepository()
      profileLocalRepo = ProfileLocalRepository()

      populateRepositories()
    }
  }

  private fun setContentWithGoogle() {
    // Mock Firebase Auth
    mockitoUtils = MockitoUtils()
    mockitoUtils.chooseCurrentUser(currentProfile.uid)

    fakeViewModel =
        HomePageViewModel(
            toDosRepository = todosLocalRepo,
            eventsRepository = eventsLocalRepo,
            profileRepository = profileLocalRepo,
            authProvider = { mockitoUtils.mockAuth })
    composeRule.setContent { HomePageScreen(homePageViewModel = fakeViewModel) }
  }

  /** Populates local repositories with fake data for testing. */
  private fun populateRepositories() = runBlocking {
    todosLocalRepo.addTodo(
        ToDo(
            uid = "3",
            name = "Plan party",
            description = "Buy decorations and invite friends",
            assigneeName = "Eve",
            dueDate = Timestamp.now(),
            dueTime = null,
            location = null,
            status = ToDoStatus.ONGOING,
            ownerId = "user1"))
    profileLocalRepo.addProfile(friend1)
    profileLocalRepo.addProfile(friend2)
    profileLocalRepo.addProfile(currentProfile)
  }

  /** Verifies that all main UI components are visible and interactable. */
  @Test
  fun componentsAreDisplayed() {
    setContentWithGoogle()
    composeRule.onNodeWithTag(HomePageScreenTestTags.UPCOMING_EVENTS_TITLE).assertIsDisplayed()
    composeRule.onNodeWithTag(HomePageScreenTestTags.UPCOMING_TASKS_TITLE).assertIsDisplayed()
    composeRule.onNodeWithTag(HomePageScreenTestTags.FOCUS_TIMER_TEXT).assertIsDisplayed()
    composeRule.onNodeWithTag(HomePageScreenTestTags.FOCUS_BUTTON).assertIsDisplayed()
    composeRule.onNodeWithTag(HomePageScreenTestTags.FOCUS_BUTTON).performClick()
  }

  /** Ensures that the focus button is visible and can be clicked without crashing. */
  @Test
  fun focusButton_isClickable() {
    setContentWithGoogle()
    composeRule
        .onNodeWithTag(HomePageScreenTestTags.FOCUS_BUTTON)
        .assertIsDisplayed()
        .performClick()
  }

  /** Verifies that task items from the ViewModel’s state are rendered in the UI. */
  @Test
  fun taskItemsAreDisplayed() {
    setContentWithGoogle()
    fakeViewModel.uiState.value.todos.forEach { todo ->
      composeRule
          .onNodeWithTag("${HomePageScreenTestTags.TASK_ITEM_PREFIX}${todo.uid}")
          .assertIsDisplayed()
    }
  }

  /** Confirms that task items exist in the composition tree for each todo in the state. */
  @Test
  fun taskItemsTextMatchesUiState() {
    setContentWithGoogle()
    fakeViewModel.uiState.value.todos.forEach { todo ->
      composeRule
          .onNodeWithTag("${HomePageScreenTestTags.TASK_ITEM_PREFIX}${todo.uid}")
          .assertIsDisplayed()
    }
  }

  /** Checks that each task item can be clicked without causing errors. */
  @Test
  fun taskItem_isClickable() {
    setContentWithGoogle()
    fakeViewModel.uiState.value.todos.forEach { todo ->
      composeRule
          .onNodeWithTag("${HomePageScreenTestTags.TASK_ITEM_PREFIX}${todo.uid}")
          .assertIsDisplayed()
          .performClick()
    }
  }

  /** Ensures the friends section is visible on the screen. */
  @Test
  fun friendsSection_isDisplayed_withAvatars() {
    setContentWithGoogle()
    composeRule.onNodeWithTag(HomePageScreenTestTags.FRIENDS_SECTION).assertIsDisplayed()
  }

  /** Verifies that the mini map is rendered and responds to click interactions. */
  @Test
  fun miniMap_isDisplayed_andClickable() {
    setContentWithGoogle()
    composeRule
        .onNodeWithTag(HomePageScreenTestTags.MINI_MAP_CARD)
        .assertIsDisplayed()
        .performClick()
  }

  /** Verifies that an anonymous user has no friends section displayed */
  @Test
  fun anonUserHasNoFriends() {
    // Create Screen with anonymous user
    // Mock Firebase Auth
    mockitoUtils = MockitoUtils()
    mockitoUtils.chooseCurrentUser(currentProfile.uid, true)
    fakeViewModel =
        HomePageViewModel(
            toDosRepository = todosLocalRepo,
            eventsRepository = eventsLocalRepo,
            profileRepository = profileLocalRepo,
            authProvider = { mockitoUtils.mockAuth })
    composeRule.setContent { HomePageScreen(homePageViewModel = fakeViewModel) }

    // Check that the friends section is not displayed
    composeRule.onNodeWithTag(HomePageScreenTestTags.FRIENDS_SECTION).assertIsNotDisplayed()
  }

  /** Verifies that friends avatars are displayed */
  @Test
  fun friendAvatars_areDisplayed_forMultipleFriends() {
    setContentWithGoogle()
    currentProfile.friendUids.forEach { uid ->
      composeRule.onNodeWithTag(getFriendAvatarTestTag(uid))
    }
  }

  /** Ensures that each friend has a visible status indicator. */
  @Test
  fun friendStatusIndicators_areDisplayed() {
    setContentWithGoogle()
    composeRule.waitForIdle()
    composeRule
        .onNodeWithTag(testTag = getFriendStatusTestTag(friend1.uid), useUnmergedTree = true)
        .assertIsDisplayed()

    composeRule
        .onNodeWithTag(getFriendStatusTestTag(friend2.uid), useUnmergedTree = true)
        .assertIsDisplayed()
  }

  /** Verifies that the empty task list text button is displayed when there are no todos */
  @Test
  fun emptyTaskList_displaysTextButton() {
    runBlocking { todosLocalRepo.deleteTodo("3") }
    setContentWithGoogle()

    composeRule
        .onNodeWithTag(
            testTag = HomePageScreenTestTags.EMPTY_TASK_LIST_TEXT_BUTTON, useUnmergedTree = true)
        .assertIsDisplayed()
  }

  /** Verifies that the empty friends message (icon + text) is displayed when user has no friends */
  @Test
  fun emptyFriends_displaysAddFriendsMessage() {
    runBlocking { profileLocalRepo.updateProfile(currentProfile.copy(friendUids = emptyList())) }
    setContentWithGoogle()

    composeRule
        .onNodeWithTag(testTag = HomePageScreenTestTags.ADD_FRIENDS_ICON, useUnmergedTree = true)
        .assertIsDisplayed()
    composeRule
        .onNodeWithTag(HomePageScreenTestTags.ADD_FRIENDS_TEXT, useUnmergedTree = true)
        .assertIsDisplayed()
  }
}
