package com.android.gatherly.model.event

import com.android.gatherly.model.group.Group
import com.android.gatherly.model.map.DisplayedMapElement
import com.android.gatherly.model.map.Location
import com.google.firebase.Timestamp

// This file contains code generated by an LLM (GitHub Copilot).

/**
 * Represents a single [Event] item within the app.
 *
 * @property id The unique identifier for the event
 * @property title The name of the event
 * @property description Details about what the event entails
 * @property creatorName The display name of the event's creator
 * @property location The geographic location where the event takes place
 * @property date The date of the event
 * @property startTime The timestamp when the event begins
 * @property endTime The timestamp when the event concludes
 * @property creatorId The user ID of the event's creator
 * @property participants List of user IDs who are attending the event
 * @property status The temporal status of the event (upcoming, ongoing, or past)
 * @property state The visibility/access level of the event (public, friends-only, or group-only)
 * @property groups List of groups associated with this event
 */
data class Event(
    val id: String,
    val title: String,
    val description: String,
    val creatorName: String,
    override val location: Location?,
    val date: Timestamp,
    val startTime: Timestamp,
    val endTime: Timestamp,
    val creatorId: String,
    val participants: List<String> = emptyList(), // contains userIds
    val status: EventStatus,
    val state: EventState = EventState.PUBLIC,
    val groups: List<Group> = emptyList(),
) : DisplayedMapElement

/** Represents the state of an [Event] item. */
enum class EventStatus {
  UPCOMING,
  ONGOING,
  PAST
}

/** Represents the kind of an [Event] item. */
enum class EventState {
  PUBLIC,
  PRIVATE_FRIENDS,
  PRIVATE_GROUP
}
