package com.android.gatherly.utils

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.widthIn
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults.buttonColors
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import com.android.gatherly.R

// This file contains code generated by an LLM (Claude.ai, GitHub Copilot).

/**
 * Data class containing callback actions for [GatherlyAlertDialog].
 *
 * @param onDismiss Callback invoked when the dismiss button is clicked or the dialog is dismissed.
 * @param onConfirm Callback invoked when the confirm button is clicked.
 * @param onNeutral Optional callback invoked when the neutral button is clicked.
 * @param onOpenAttendeesList Optional callback invoked when the attendees button is clicked.
 */
data class GatherlyAlertDialogActions(
    val onDismiss: () -> Unit,
    val onConfirm: () -> Unit,
    val onNeutral: (() -> Unit)? = null,
    val onOpenAttendeesList: (() -> Unit)? = null
)

/**
 * A custom alert dialog component for the Gatherly app.
 *
 * Displays a modal dialog with title, body text, and dismiss/confirm buttons. Optionally supports
 * event details (creator, date/time), a neutral action button, and an attendees button. Uses a
 * custom [Dialog] implementation with [Surface] for full layout control and semantic correctness.
 *
 * The dismiss and confirm buttons are displayed with equal width in a row layout. When provided,
 * the neutral button appears below the body text, and the attendees button appears in the title
 * row.
 *
 * @param titleText The main title text displayed at the top of the dialog.
 * @param bodyText The body/description text displayed below the title.
 * @param dismissText The text for the dismiss button (typically "Cancel" or "Back").
 * @param confirmText The text for the confirm button (typically "OK" or an action verb).
 * @param actions The callback actions for the dialog buttons.
 * @param creatorText Optional creator name to display as "By [creatorText]". Only displayed if not
 *   null or blank.
 * @param dateText Optional date string for event details (e.g., "25/12/2025").
 * @param startTimeText Optional start time for event details (e.g., "14:00"). Displayed only if
 *   [dateText] is provided.
 * @param endTimeText Optional end time for event details (e.g., "16:00"). Displayed only if
 *   [dateText] is provided.
 * @param isImportantWarning If true, styles the confirm button with error colours to indicate a
 *   destructive or important action (e.g., deletion). Defaults to false.
 * @param confirmEnabled Whether the confirm button is enabled and clickable. Defaults to true.
 * @param neutralText Optional text for a third neutral action button. The button is only displayed
 *   if this parameter is not null.
 * @param neutralEnabled Whether the neutral button is enabled and clickable. Defaults to true.
 * @param numberAttendees Optional number of attendees to display in the attendees button. The
 *   button is only displayed if this parameter is not null.
 *
 * Example usage:
 * ```
 * GatherlyAlertDialog(
 *     titleText = "Delete Event",
 *     bodyText = "Are you sure you want to delete this event?",
 *     dismissText = "Cancel",
 *     confirmText = "Delete",
 *     isImportantWarning = true,
 *     actions = GatherlyAlertDialogActions(
 *         onDismiss = { /* handle dismiss */ },
 *         onConfirm = { /* handle deletion */ }
 *     )
 * )
 * ```
 */
@Composable
fun GatherlyAlertDialog(
    titleText: String,
    bodyText: String,
    dismissText: String,
    confirmText: String,
    actions: GatherlyAlertDialogActions,
    creatorText: String? = null,
    dateText: String? = null,
    startTimeText: String? = null,
    endTimeText: String? = null,
    isImportantWarning: Boolean = false,
    confirmEnabled: Boolean = true,
    neutralText: String? = null,
    neutralEnabled: Boolean = true,
    numberAttendees: Int? = null,
) {
  Dialog(
      onDismissRequest = actions.onDismiss,
      properties = DialogProperties(usePlatformDefaultWidth = false)) {
        Surface(
            modifier =
                Modifier.padding(dimensionResource(R.dimen.padding_screen))
                    .fillMaxWidth()
                    .testTag(AlertDialogTestTags.ALERT),
            shape = MaterialTheme.shapes.extraLarge,
            color = MaterialTheme.colorScheme.surfaceVariant,
            tonalElevation = 6.dp) {
              Column(
                  modifier = Modifier.padding(dimensionResource(R.dimen.padding_screen)),
                  verticalArrangement =
                      Arrangement.spacedBy(
                          dimensionResource(R.dimen.spacing_between_fields_medium))) {

                    // Title Section
                    Column {
                      Row(
                          verticalAlignment = Alignment.CenterVertically,
                          modifier = Modifier.fillMaxWidth()) {
                            // Left spacer to balance the button on the right
                            if (numberAttendees != null) {
                              Spacer(
                                  modifier =
                                      Modifier.height(dimensionResource(R.dimen.padding_large))
                                          .widthIn(min = dimensionResource(R.dimen.padding_large)))
                            }

                            // Centered title
                            Text(
                                text = titleText,
                                textAlign = TextAlign.Center,
                                style = MaterialTheme.typography.titleLarge,
                                color = MaterialTheme.colorScheme.onSurfaceVariant,
                                modifier = Modifier.weight(1f).testTag(AlertDialogTestTags.TITLE))

                            // Attendees button on the right (if present)
                            if (numberAttendees != null) {
                              Button(
                                  colors =
                                      buttonColors(
                                          containerColor =
                                              MaterialTheme.colorScheme.secondaryContainer,
                                          contentColor =
                                              MaterialTheme.colorScheme.onSecondaryContainer),
                                  contentPadding =
                                      PaddingValues(
                                          horizontal =
                                              dimensionResource(R.dimen.padding_extra_small),
                                          vertical =
                                              dimensionResource(
                                                  R.dimen.padding_extra_small_vertical)),
                                  onClick = { actions.onOpenAttendeesList?.invoke() },
                                  modifier =
                                      Modifier.testTag(AlertDialogTestTags.ATTENDEES_BTN)
                                          .height(dimensionResource(R.dimen.padding_large))
                                          .widthIn(
                                              min = dimensionResource(R.dimen.padding_large))) {
                                    BoxNumberAttendees(numberAttendees)
                                  }
                            }
                          }

                      // Event details (creator, date, time)
                      GatherlyDialogTitleContent(
                          creatorText = creatorText,
                          dateText = dateText,
                          startTimeText = startTimeText,
                          endTimeText = endTimeText)
                    }

                    // Body Section
                    Column(horizontalAlignment = Alignment.CenterHorizontally) {
                      Text(
                          text = bodyText,
                          textAlign = TextAlign.Center,
                          color = MaterialTheme.colorScheme.onSurfaceVariant,
                          modifier = Modifier.testTag(AlertDialogTestTags.BODY))

                      // Neutral button (if present)
                      neutralText?.let { text ->
                        Spacer(
                            modifier = Modifier.height(dimensionResource(R.dimen.padding_screen)))
                        Button(
                            colors =
                                buttonColors(
                                    containerColor = MaterialTheme.colorScheme.primaryContainer,
                                    contentColor = MaterialTheme.colorScheme.onPrimaryContainer),
                            onClick = { actions.onNeutral?.invoke() },
                            enabled = neutralEnabled,
                            modifier =
                                Modifier.fillMaxWidth().testTag(AlertDialogTestTags.NEUTRAL_BTN)) {
                              Text(text = text)
                            }
                      }
                    }

                    // Bottom Buttons Section
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                          // Dismiss Button
                          Button(
                              colors =
                                  buttonColors(
                                      containerColor = MaterialTheme.colorScheme.primaryContainer,
                                      contentColor = MaterialTheme.colorScheme.onPrimaryContainer),
                              onClick = actions.onDismiss,
                              modifier =
                                  Modifier.weight(1f).testTag(AlertDialogTestTags.DISMISS_BTN)) {
                                Text(
                                    text = dismissText,
                                    color = MaterialTheme.colorScheme.onPrimaryContainer,
                                    textAlign = TextAlign.Center,
                                    maxLines = 1)
                              }

                          // Confirm Button
                          Button(
                              colors =
                                  buttonColors(
                                      containerColor =
                                          if (isImportantWarning) {
                                            MaterialTheme.colorScheme.surfaceVariant
                                          } else {
                                            MaterialTheme.colorScheme.primaryContainer
                                          },
                                      contentColor = contentColor(isImportantWarning)),
                              enabled = confirmEnabled,
                              onClick = actions.onConfirm,
                              modifier =
                                  Modifier.weight(1f).testTag(AlertDialogTestTags.CONFIRM_BTN)) {
                                Text(
                                    text = confirmText,
                                    color = contentColor(isImportantWarning),
                                    textAlign = TextAlign.Center,
                                    maxLines = 1)
                              }
                        }
                  }
            }
      }
}

@Composable
private fun contentColor(isImportantWarning: Boolean): Color {
  return if (isImportantWarning) {
    MaterialTheme.colorScheme.error
  } else {
    MaterialTheme.colorScheme.onPrimaryContainer
  }
}

@Composable
private fun GatherlyDialogTitleContent(
    creatorText: String?,
    dateText: String?,
    startTimeText: String?,
    endTimeText: String?
) {

  if (dateText == null || startTimeText == null || endTimeText == null) return

  // Add spacing between title and creator/date info
  Spacer(modifier = Modifier.height(dimensionResource(R.dimen.padding_small)))

  if (!creatorText.isNullOrBlank()) {
    Text(
        text = "By $creatorText",
        textAlign = TextAlign.Center,
        style = MaterialTheme.typography.bodyMedium,
        color = MaterialTheme.colorScheme.onSurfaceVariant,
        modifier = Modifier.fillMaxWidth().testTag(AlertDialogTestTags.CREATOR_TEXT))

    // Small spacing between creator and date
    Spacer(modifier = Modifier.height(dimensionResource(R.dimen.padding_extra_small)))
  }

  Text(
      text = "On $dateText from $startTimeText to $endTimeText",
      textAlign = TextAlign.Center,
      style = MaterialTheme.typography.bodyMedium,
      color = MaterialTheme.colorScheme.onSurfaceVariant,
      modifier = Modifier.fillMaxWidth().testTag(AlertDialogTestTags.DATE_TEXT))
}

object AlertDialogTestTags {
  const val ALERT = "alert"
  const val TITLE = "title"
  const val BODY = "body"
  const val DISMISS_BTN = "dismissButton"
  const val CONFIRM_BTN = "confirmButton"
  const val NEUTRAL_BTN = "neutralButton"
  const val CREATOR_TEXT = "creatorText"
  const val DATE_TEXT = "dateText"
  const val ATTENDEES_BTN = "attendeesButton"
}
